# Homework
Given the dataset of Google Playstore below:
<br>[https://www.kaggle.com/lava18/google-play-storeapps#googleplaystore.csv](https://www.kaggle.com/lava18/google-play-storeapps#googleplaystore.csv)
<br>Create a Jupyter Notebook or Google Collabs to answer
<br>more less about the followings :

Author : Randy Galawana
<br>Created on : October 1st, 2019
<br>Email : [mailto:randy_galawana1@telkomsel.co.id](randy_galawana1@telkomsel.co.id)
***

### Load Data

In [199]:
import pandas as pd
import numpy as np

url='https://raw.githubusercontent.com/galawana/DSA_Python/master/Google_Play_Datasets/googleplaystore.csv'
df = pd.read_csv(url, encoding='utf-8')

df.head(2)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up

### Data Cleansing

In [200]:
min_rating = df['Rating'].min()
max_rating = df['Rating'].max()
print("rating from ",min_rating," to ",max_rating,", it's should be between 0 .0 to 5.0, so there is some missplace on index ",df[df['Rating'] == 19].index)
print("\ndata index 10472 is shifting to left from column Category onwards, so we should shift 1 to right from Category")

df.iloc[10472,1:] = df.iloc[10472,1:].shift(1)

rating from  1.0  to  19.0 , it's should be between 0 .0 to 5.0, so there is some missplace on index  Int64Index([10472], dtype='int64')

data index 10472 is shifting to left from column Category onwards, so we should shift 1 to right from Category

## Main Case

### 1. How many rows and columns reflected on dataset file googleplaystore.csv?

In [201]:
print("dataset file googleplaystore.csv shape is ",df.shape)
print("kolom : ", len(df.columns),", baris : ",len(df))

dataset file googleplaystore.csv shape is  (10841, 13)
kolom :  13 , baris :  10841

#### further cleaning data

In [202]:
print("\nRemove Duplicates Apps")
df.drop_duplicates(subset='App', inplace=True)
print("\nRemove + and commas from installs and change to Int")
df['Installs'] = df['Installs'].apply(lambda x: x.replace('+', '') if '+' in str(x) else x)
df['Installs'] = df['Installs'].apply(lambda x: x.replace(',', '') if ',' in str(x) else x)
df['Installs'] = df['Installs'].astype(int)

print("\nChange rating to float")
df['Rating'] = df['Rating'].astype(float)
print("\nChange Reviews to Int")
df['Reviews'] = df['Reviews'].astype(int)

df.info()

Remove Duplicates Apps

Remove + and commas from installs and change to Int

Change rating to float

Change Reviews to Int
<class 'pandas.core.frame.DataFrame'>
Int64Index: 9660 entries, 0 to 10840
Data columns (total 13 columns):
App               9660 non-null object
Category          9659 non-null object
Rating            8197 non-null float64
Reviews           9660 non-null int32
Size              9660 non-null object
Installs          9660 non-null int32
Type              9659 non-null object
Price             9660 non-null object
Content Rating    9660 non-null object
Genres            9659 non-null object
Last Updated      9660 non-null object
Current Ver       9652 non-null object
Android Ver       9658 non-null object
dtypes: float64(1), int32(2), object(10)
memory usage: 981.1+ KB

### 2. How many unique app categories that cover in this dataset?

In [213]:
category = df[['Category']]
print("Unique Category : ",len(category.groupby(['Category'])))

res = pd.get_dummies(df['Genres'].str.split(';').apply(pd.Series).stack()).sum(level=0)
print("Unique Genre : ",len(res.columns))

Unique Category :  33
Unique Genre :  53

### 3. What are top 3 apps that have highest number of users installed/download among all categories?

In [214]:
apps_install = df.sort_values('Installs',ascending=False)
apps_install.loc[:,['App','Category','Installs']].head(3)

                     App             Category    Installs
336   WhatsApp Messenger        COMMUNICATION  1000000000
152    Google Play Books  BOOKS_AND_REFERENCE  1000000000
1654      Subway Surfers                 GAME  1000000000

### 4. What are top 3 apps that have highest number of users installed/download among the following categories

In [215]:
list_of_category = ["BUSINESS", "COMMUNICATION", "GAME", "DATING", "MUSIC"]
data_category = df[df['Category'].isin(list_of_category)]
data_install = data_category.groupby(['Category'])
data_install = data_install.apply(lambda x: x.sort_values(["Installs"],ascending=False))
data_install = data_install[['App','Category','Installs']].reset_index(drop=True)
data_install.groupby(['Category']).head(3)

                                          App       Category    Installs
0      File Commander - File Manager/Explorer       BUSINESS   100000000
1      OfficeSuite : Free Office + PDF Editor       BUSINESS   100000000
2                           Indeed Job Search       BUSINESS    50000000
420  Messenger – Text and Video Chat for Free  COMMUNICATION  1000000000
421             Skype - free IM & video calls  COMMUNICATION  1000000000
422                        WhatsApp Messenger  COMMUNICATION  1000000000
735              Hitwe - meet people and chat         DATING    10000000
736                  Moco - Chat, Meet People         DATING    10000000
737        Chat Rooms, Avatars, Date - Galaxy         DATING    10000000
906                            Subway Surfers           GAME  1000000000
907                          Candy Crush Saga           GAME   500000000
908                              Temple Run 2           GAME   500000000

### 5. What are top 3 apps that have highest rating among the following categories:

In [216]:
data_rating = data_category.groupby(['Category'])
data_rating = data_rating.apply(lambda x: x.sort_values(["Rating"],ascending=False))
data_rating = data_rating[['App','Category','Rating']].reset_index(drop=True)
data_rating.groupby(['Category']).head(3)

                                            App       Category  Rating
0                              CP Installer App       BUSINESS     5.0
1                                      BJ Foods       BUSINESS     5.0
2                                CJ the REALTOR       BUSINESS     5.0
420                                          BV  COMMUNICATION     5.0
421                                     chat dz  COMMUNICATION     5.0
422                                EJ messenger  COMMUNICATION     5.0
735                       Spine- The dating app         DATING     5.0
736  Girls Live Talk - Free Text and Video Chat         DATING     5.0
737                     Online Girls Chat Group         DATING     5.0
906                                      211:CK           GAME     5.0
907                                    EC Mover           GAME     5.0
908                 Santa's Monster Shootout DX           GAME     5.0

### 6. If you use two criteria (installs and rating), what are top 3 apps for the following categories?

In [217]:
data_both = data_category.groupby(['Category'])
data_both = data_both.apply(lambda x: x.sort_values(["Installs","Rating"],ascending=False))
data_both = data_both[['App','Category','Installs','Rating']].reset_index(drop=True)
data_both.groupby(['Category']).head(3)

,App,Category,Installs,Rating
0,OfficeSuite : Free Office + PDF Editor,BUSINESS,100000000,4.3
1,File Commander - File Manager/Explorer,BUSINESS,100000000,4.3
2,"Vault-Hide SMS,Pics & Videos,App Lock,Cloud ba...",BUSINESS,50000000,4.5
420,WhatsApp Messenger,COMMUNICATION,1000000000,4.4
421,Google Chrome: Fast & Secure,COMMUNICATION,1000000000,4.3
422,Gmail,COMMUNICATION,1000000000,4.3
735,Find Real Love — YouLove Premium Dating,DATING,10000000,4.5
736,"Chat Rooms, Avatars, Date - Galaxy",DATING,10000000,4.3
737,"Moco - Chat, Meet People",DATING,10000000,4.2
906,Subway Surfers,GAME,1000000000,4.5
907,My Talking Tom,GAME,500000000,4.5
908,Candy Crush Saga,GAME,500000000,4.4

## Another Case

### Match Apps and Category based on provided dataset!

In [218]:
list_apps = ["Flipboard: News For Our Time", "WhatsApp Messenger", "Subway Surfers", "Pinterest", "DU Battery Saver - Battery Charger & Battery Life", "FIFA Soccer", "Dropbox", "File Commander - File Manager/Explorer"]
data_apps = df[df['App'].isin(list_apps)]
data_apps[['App','Category']]

                                                     App            Category
336                                   WhatsApp Messenger       COMMUNICATION
1654                                      Subway Surfers                GAME
2552                                           Pinterest              SOCIAL
3473                                             Dropbox        PRODUCTIVITY
3755                        Flipboard: News For Our Time  NEWS_AND_MAGAZINES
8445                                         FIFA Soccer              SPORTS
8896   DU Battery Saver - Battery Charger & Battery Life               TOOLS
10253             File Commander - File Manager/Explorer            BUSINESS

### Apps with 1 billion user

In [219]:
df[df['Installs']>=1000000000].App

152                            Google Play Books
335     Messenger – Text and Video Chat for Free
336                           WhatsApp Messenger
338                 Google Chrome: Fast & Secure
340                                        Gmail
341                                     Hangouts
391                Skype - free IM & video calls
865                            Google Play Games
1654                              Subway Surfers
2544                                    Facebook
2545                                   Instagram
2554                                     Google+
2808                               Google Photos
3117                   Maps - Navigate & Explore
3127                          Google Street View
3234                                      Google
3454                                Google Drive
3665                                     YouTube
3687                     Google Play Movies & TV
3736                                 Google News
Name: App, dtype: object

### Arrange top 5 COMMUNICATION category apps from the highest number of reviews to the lowest!

In [220]:
apps_com = df[df['Category']=='COMMUNICATION']
apps_com = apps_com.sort_values('Reviews',ascending=False)
apps_com.loc[:,['App','Category','Reviews']].head(10)

,App,Category,Reviews
336,WhatsApp Messenger,COMMUNICATION,69119316
335,Messenger – Text and Video Chat for Free,COMMUNICATION,56642847
378,UC Browser - Fast Download Private & Secure,COMMUNICATION,17712922
406,BBM - Free Calls & Messages,COMMUNICATION,12842860
342,Viber Messenger,COMMUNICATION,11334799
403,LINE: Free Calls & Messages,COMMUNICATION,10790289
391,Skype - free IM & video calls,COMMUNICATION,10484169
338,Google Chrome: Fast & Secure,COMMUNICATION,9642995
449,"Truecaller: Caller ID, SMS spam blocking & Dialer",COMMUNICATION,7820209
365,WeChat,COMMUNICATION,5387333

### Arrange top 3 games category apps based on number of installed and review!

In [221]:
apps_game = df[df['Category']=='GAME']
apps_game = apps_game.sort_values(['Installs','Reviews'],ascending=False)
apps_game.loc[:,['App','Category','Installs','Reviews']].head(10)

                   App Category    Installs   Reviews
1654    Subway Surfers     GAME  1000000000  27722264
1655  Candy Crush Saga     GAME   500000000  22426677
1722    My Talking Tom     GAME   500000000  14891223
1662               Pou     GAME   500000000  10485308
1661      Temple Run 2     GAME   500000000   8118609
1670    Clash of Clans     GAME   100000000  44891723
1660      Clash Royale     GAME   100000000  23133508
1675       8 Ball Pool     GAME   100000000  14198297
1932    Shadow Fight 2     GAME   100000000  10979062
1764        Pokémon GO     GAME   100000000  10424925